#Test cases for the job portal API
###
# Api route for user signup
POST http://localhost:8000/user/signup
Content-Type: application/json

{
  "name": "testuser",
  "email": "rushendra@gmail.com",
  "password": "1234"
  
}


###
POST http://localhost:8000/user/verify-email
Content-Type: application/json

{
  "email":"rushendrakumar17@gmail.com",
  "verificationCode":"650218"
}

###
# Api route for getting all jobs
GET http://localhost:8000/jobs/getAll


###
#Api route for creating a new job
POST http://localhost:8000/jobs/add
Content-Type: application/json

{
  "title": "Cloud engineer",
  "description": "We are looking for a DevOps engineer to join our team. The ideal candidate should have experience in managing cloud infrastructure, CI/CD pipelines, and container orchestration.",
  "company": "Scale orange",
  "skills": [
    "React",
    "Angular"
  ],
  "location": ["Bangalore"],
  "yearsOfExperience": "2",
  "salary": "100000",
  "gender": "male",
  "languagesKnown": [
    "English",
    "Hindi"
  ],
  "requirements":[
    "Good communication skills",
    "Ability to work in a team",
    "Problem-solving skills"
  ],
  "degrees": [
    "B.Tech"
  ],
  "minYearOfGraduation": "2022",
  "maxYearOfGraduation": "2028",
  "branch": "CSE"
}

###
# Api route for getting a job by ID
GET http://localhost:8000/jobs/getById/1


###
# Api route for deleting a job
DELETE http://localhost:8000/jobs/delete/1


###
# Api route for admin signup
POST http://localhost:8000/admin/signup
Content-Type: application/json

{
  "name": "adminuser",
  "email": "admin@gmail.com",
  "password": "1234",
  "company": "Scale orange",
  "location": "Chennai",
  "phone": "1234567890"
}

###
# Api route for admin verification
POST http://localhost:8000/admin/verify
Content-Type: application/json

{
  "email": "testuser@gmail.com",
  "verificationCode": "645156"
}

###
# Api route for admin login
POST http://localhost:8000/admin/signin
Content-Type: application/json

{
  "email": "testuser@gmail.com",
  "password": "1234"
}

###
# Api route for applying for a job
GET http://localhost:8000/jobs/apply/3

###
# Api route for getting all applications
GET http://localhost:8000/jobs/1/applications

###
# Api route for editing a job
PUT http://localhost:8000/jobs/edit/3
Content-Type: application/json

{
  "title": "Cloud engineer",
  "description": "We are looking for a DevOps engineer to join our team. The ideal candidate should have experience in managing cloud infrastructure, CI/CD pipelines, and container orchestration.",
  "company": "Scale orange",
  "skills": [
    "React",
    "Angular"
  ],
  "location": ["Bangalore"],
  "yearsOfExperience": "2",
  "salary": "100000",
  "gender": "male",
  "languagesKnown": [
    "English",
    "Hindi"
  ],
  "requirements":[
    "Good communication skills",
    "Ability to work in a team",
    "Problem-solving skills"
  ],
  "degrees": [
    "B.Tech"
  ],
  "minYearOfGraduation": "2022",
  "maxYearOfGraduation": "2028",
  "branch": "CSE"
}


###

GET http://localhost:8000/user/getById/1



###
GET http://localhost:8000/date


###
GET http://localhost:8000/user/getEnrolledJobs/1



###
POST http://localhost:8000/jobs/1/comment/
Content-Type: application/json

{
  "comment": "Good job",
  "sender": "Rushendra"
}


###
POST http://localhost:8000/mela/create
Content-Type: application/json

{
  "name": "Prakasam Mega Job Mela 2025",
  "description": "",
  "startDate": "2025-2-14",
  "endDate": "2025-2-15",
  "location": ["16.0472","79.3073"], 
  "area": "Dr. BR Ambedkar Auditorium, Yerragonda Palem"
}


###
GET http://localhost:8000/mela/getMela/1



###
POST http://localhost:8000/user/google-form-data
Content-Type: application/json

{
  "timestamp": "2025-06-04T07:56:56.263Z",
  "responses": {
    "Name": "Rushendra",
    "Gender":"Male",
    "Phone": "1234567890",
    "Email": "rushendrakumar17@gmail.com",
    "Years Of Experience": "3",
    "Skills (Comma Seperated )": "React,Angular",
    "Degrees (Comma Seperated )": "B.Tech,M.Tech",
    "Address": "Home",
    "Year Of Graduation": "2024",
    "Languages( Comma Seperated )": "English,Telugu,Hindi",
    "CV": [ "1_rAitKoIW1DXcH4SwCfITedk9s5TXHBG" ]
  }
}